# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    container_name: meu_app_django
    command: gunicorn --bind 0.0.0.0:7221 core.wsgi:application
    volumes:
      - static_data:/app/staticfiles  # Volume para arquivos estáticos
      - db_data:/app/data             # Volume para o banco de dados
    ports:
      - "7221:7221"
    env_file:
      - .env  # Carrega as variáveis de ambiente do seu arquivo .env

volumes:
  static_data:
  db_data: