# Generated by Django 5.2.1 on 2025-08-07 22:02

import django.db.models.deletion
import parler.fields
import parler.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='about_page/', verbose_name='Imagem de Cabeçalho')),
            ],
            options={
                'verbose_name': 'Página Sobre',
                'verbose_name_plural': 'Página Sobre',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('first_name', models.CharField(editable=False, max_length=100, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(blank=True, editable=False, max_length=155, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Foto de Perfil')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL do LinkedIn')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL do Instagram')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Apenas números, incluindo código do país e DDD. Ex: 5511999999999', max_length=20, verbose_name='WhatsApp')),
                ('is_team_member', models.BooleanField(default=True, verbose_name='É membro da equipe principal?')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Autor (e Membro da Equipe)',
                'verbose_name_plural': 'Autores (e Membros da Equipe)',
                'ordering': ['full_name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Imagem da Categoria')),
                ('color', models.CharField(blank=True, choices=[('#94a3b8', 'Cinza'), ('#f87171', 'Vermelho'), ('#fb923c', 'Laranja'), ('#fbbf24', 'Âmbar'), ('#86efac', 'Lima'), ('#4ade80', 'Verde'), ('#67e8f9', 'Ciano'), ('#60a5fa', 'Azul'), ('#818cf8', 'Índigo'), ('#a78bfa', 'Violeta')], default='#94a3b8', max_length=7, null=True, verbose_name='Cor da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name': 'Mensagem de Contato',
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do Assinante')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
            ],
            options={
                'verbose_name': 'Assinante da Newsletter',
                'verbose_name_plural': 'Assinantes da Newsletter',
                'ordering': ('-subscribed_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True, verbose_name='URL do Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL do LinkedIn')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Apenas números, incluindo código do país e DDD. Ex: 5511999999999', max_length=20, verbose_name='Número do WhatsApp')),
                ('posts_in_home_grid', models.PositiveIntegerField(default=8, help_text="Defina quantos posts (excluindo o de destaque) devem aparecer na seção 'Artigos Recentes'.", verbose_name='Nº de Posts na Grade da Página Inicial')),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Imagem de Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='published', max_length=10, verbose_name='Status')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Ordem')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.author', verbose_name='Autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('order',),
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Título Principal')),
                ('subtitle', models.TextField(verbose_name='Subtítulo')),
                ('content', tinymce.models.HTMLField(verbose_name='Conteúdo Completo da Página')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.aboutpage')),
            ],
            options={
                'verbose_name': 'Página Sobre Translation',
                'db_table': 'blog_aboutpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AuthorTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Cargo (Ex: Editor-Chefe)')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.author')),
            ],
            options={
                'verbose_name': 'Autor (e Membro da Equipe) Translation',
                'db_table': 'blog_author_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.category')),
            ],
            options={
                'verbose_name': 'Categoria Translation',
                'db_table': 'blog_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Este campo será preenchido automaticamente.', max_length=200, unique=True)),
                ('content', tinymce.models.HTMLField(verbose_name='Conteúdo')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Translation',
                'db_table': 'blog_post_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('site_name', models.CharField(default='MudarNome', max_length=100, verbose_name='Nome do Site')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='blog.sitesettings')),
            ],
            options={
                'verbose_name': 'Configurações do Site Translation',
                'db_table': 'blog_sitesettings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
