# Generated by Django 5.2.4 on 2025-08-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Resumo atrativo para o Google (máx. 160 caracteres).', max_length=160, verbose_name='Descrição para SEO (Meta Description)'),
        ),
        migrations.AddField(
            model_name='posttranslation',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Otimizado para buscadores (máx. 60 caracteres). Se vazio, usa o título principal.', max_length=60, verbose_name='Título para SEO (Meta Title)'),
        ),
    ]
