# Generated by Django 5.2.4 on 2025-08-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posttranslation_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Categoria'),
        ),
    ]
