# Generated by Django 5.2.4 on 2025-08-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_categorytranslation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpagetranslation',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Faça o upload de uma imagem (.ico, .png, .svg) para ser o ícone nas abas do navegador.', null=True, upload_to='favicons/', verbose_name='Ícone do Site (Favicon)'),
        ),
    ]
