# Generated by Django 5.2.4 on 2025-08-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_aboutpagetranslation_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Faça o upload da imagem do logo para o cabeçalho. Se deixado em branco, o nome do site será usado como texto.', null=True, upload_to='logos/', verbose_name='Logo do Site'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_name_with_logo',
            field=models.BooleanField(default=False, help_text='Se marcado, o nome do site aparecerá ao lado da imagem do logo no cabeçalho.', verbose_name='Exibir nome do site junto com o logo?'),
        ),
    ]
