# Generated by Django 5.2.4 on 2025-08-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_sitesettings_logo_sitesettings_show_name_with_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Gerado automaticamente a partir do nome.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Gerado automaticamente a partir do título.', max_length=200, unique=True),
        ),
    ]
