# Generated by Django 5.2.4 on 2026-06-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_author_slug_alter_categorytranslation_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='Se configurada, cada post salvo será traduzido automaticamente para Inglês, Espanhol e Francês. Também ativa o seletor de idioma no rodapé do site.', max_length=250, verbose_name='Chave API Groq (Tradução Automática)'),
        ),
    ]
