# Generated by Django 5.2.4 on 2026-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_add_groq_api_key_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(blank=True, default='', help_text='Separadas por vírgula. Geradas pelo pipeline IA para artigos relacionados.', max_length=300, verbose_name='Palavras-chave'),
        ),
    ]
