# Generated by Django 5.2.4 on 2026-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_add_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Suporta MP4, WebM, MOV. Exibido no lugar da imagem quando presente.', null=True, upload_to='videos/', verbose_name='Vídeo de Destaque'),
        ),
    ]
